version: '3.7'

services:

  configserver:
    image: config:1
    build:
      context: ./configserver
      dockerfile: Dockerfile
    volumes:
      - /tmp/cloud
    ports:
      - "8888:8888"
    networks:
     - backend
    restart: always
    deploy:
     resources:
      limits: 
       memory: 64mb
      reservations:
       memory: 64mb
       
  zipkin:
    image: zipkin:1
    build:
      context: ./zipkin
      dockerfile: Dockerfile
    volumes:
      - /tmp/cloud
    ports:
      - "9411"
    networks:
     - backend
    restart: always
    deploy:
     resources:
      limits: 
       memory: 64mb
      reservations:
       memory: 64mb       
             
  eureka:
    image: eureka:1
    build:
      context: ./eureka
      dockerfile: Dockerfile
    volumes:
      - /tmp/cloud
    ports:
      - "8761:8761"
    depends_on:
      - "zipkin"      
    environment:
      - "SPRING_ZIPKIN_BASEURL=http://zipkin:9411/"
    networks:
     - backend
    restart: always
    deploy:
     resources:
      limits: 
       memory: 64mb
      reservations:
       memory: 64mb

      
  ms:
    image: ms:1
    build:
      context: ./microservice
      dockerfile: Dockerfile
    volumes:
      - /tmp/cloud
    ports:
      - "8090:8090"
    networks:
     - backend      
    depends_on:
      - "configserver"
      - "eureka"
      - "zipkin"
    # Pass environment variables to the service
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka"
      - "CLOUD_CONFIG_URI=http://configserver:8888/"
      - "SPRING_ZIPKIN_BASEURL=http://zipkin:9411/"
      
    restart: always
    deploy:
     resources:
      limits: 
       memory: 64mb
      reservations:
       memory: 64mb
       
# Networks to be created to facilitate communication between containers
networks:
  backend:       
       