spring:
 application:
  name: apiGateway
  
server:
 port: 9090
 
 zuul:
  ignoredServices: '*'
  ribbon:
    eager-load:
      enabled: true
  routes:
   product-service:
    path: /product/**
    serviceId: ms
    stripPrefix: true
      
 
eureka:
 instance:
  preferIpAddress: true
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}