spring:
 application:
  name: apiGateway
  
server:
 port: 9090
 
 zuul:
  ribbon:
    eager-load:
      enabled: true
      
 
 
eureka:
 instance:
  preferIpAddress: true
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}