spring:
 application:
  name: apiGateway
 cloud:
   config:
     enabled: true  
  
server:
 port: ${SERVER_PORT:9090}
 
 zuul:
  ignoredServices: '*'
  ribbon:
    eager-load:
      enabled: true
  routes:
   product-service:
    path: /product/**
    serviceId: ms
      
 
eureka:
 instance:
  preferIpAddress: true
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
   
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
logging:
  level:
    com.netflix: 'TRACE'
    org.springframework.cloud: 'TRACE'
