server:
  port: ${SERVER_PORT:8761}
eureka:
  instance:
   hostname: ${EUREKA_INSTANCE_HOSTNAME:eureka}
   appname: ${EUREKA_INSTANCE_APPNAME:eureka-cluster}
   shouldBatchReplication: true   
  server:
   eviction-interval-timer-in-ms: 25000
   enableSelfPreservation: false
  client:
    health-check:
     enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}    
       
spring:
 zipkin:
  baseUrl: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411/}
  

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      # By default, only 'health' and 'info' are accessible via web
      exposure:
        include: '*'      
logging:
 level: 
  com:
   netflix:
    eureka: DEBUG
    discovery: DEBUG
       