server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    
spring:
 zipkin:
  baseUrl: http://localhost:9411/
  

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      # By default, only 'health' and 'info' are accessible via web
      exposure:
        include: '*'      