server:
 port: ${SERVER_PORT:8888}
 
spring:
  profiles:
   active: native
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
          
          
logging: 
 level :
  jdbc: OFF
  sqltiming: DEBUG
  resultsettable: DEBUG         