server:
 port: 8090

spring:
 application:
  name: ms
 zipkin:
  baseUrl: http://localhost:9411/        

 cloud :
 #Configurazione per il servizio di configurazione applicativa
  config :
   uri: http://localhost:8888/
   
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
