server:
 port: 8090

spring:
 main:
  lazy-initialization: true
 application:
  name: ms
#ZipKin  
 zipkin:
  baseUrl: http://localhost:9411/

 cloud :
#Config Server
  config :
   uri: http://localhost:8888/
   fail-fast: true
   retry:
     max-attempts: 20   
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    
