server:
 port: ${SERVER_PORT:8090}

spring:
 main:
  lazy-initialization: true
 application:
  name: ms
 jpa :
  database: POSTGRESQL
  show-sql : true
  generate-ddl : true
  hibernate:
   ddl-auto: update
  properties.hibernate.jdbc.lob.non_contextual_creation: true
 datasource:
  platform: postgres
  url: ${SPRING_DB_URL:jdbc:postgresql://localhost:5432/demo}
  username: ${SPRING_DB_USERNAME:demo}
  password: ${SPRING_DB_PASSWORD:demo}

  
#ZipKin  
 zipkin:
  baseUrl: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411/}

 cloud :
#Config Server
  config :
   uri: ${SPRING_CONFIG_URL:http://127.0.0.1:8888/}
   fail-fast: true
   retry:
     max-attempts: 20   
   
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
  

    

security:
 basic:
  enable: false   
  
management:
 security:
  enabled: false
  
service:
 ms:
  serviceId: ms