server:
 port: 8090

spring:
 application:
  name: ms
 zipkin:
  baseUrl: http://localhost:9411/        

 cloud :
 #Config Server
  config :
   uri: http://localhost:8888/
   fail-fast: true
   retry:
     max-attempts: 20   
   
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
